### ISSUE TITLE
Not getting any pushes on my Mac desktop anymore

### ISSUE THREAD

**Issue by shoguevara** [sidneys/pb-for-desktop#100]
I have pushbullet app on my phone and sidneys pb-for-dekstop on my Mac and my Ubuntu desktop.
For some reason I no longer receiving any notifications on my MacBook installation. Tried resetting the app configuration, reinstalling from scratch, muting/unmuting.
Unfortunately nothing works.
Embedded test notification works fine, so it's not the notification permission problem. But I don't get any synced notifications from my phone and the ones I intentionally send from my phone to the Mac.
Could anyone pls advise where else to look to dig deeper?
**App Version**
v8.9.5
**Installation Type** 
Setup
**Operating System**
Mac OS Mojave 10.14.3

**Comment by shoguevara** [comment]
Upgraded to 8.10.1 - the issue is still there.
I also can confirm, that I can send notifications from pb-for-dekstop to mobile client, SMS mirroring also works. Just not getting notifications on Mac desktop.
I also can confirm, that pushes work fine for chrome app on my Mac too, but it's not the option to use it! I love pb-for-dekstop!

**Comment by shoguevara** [comment]
I also just received notification from connected IFTT service on my Mac...

**Comment by mihovilm** [comment]
Same

**Comment by ldodge94** [comment]
I'm also dealing with this same issue. I'm on version 8.12 and I've repeatedly resent configuration and reconnected to my android phone by no dice. Running Mojave.

**Comment by fernandex00** [comment]
Same here on Ubuntu 18.10

**Comment by SorrowfulMercies** [comment]
Not getting notifications on Windows 10 either

**Comment by noranyan** [comment]
The issue still exists.

I can send pushes from Mac to other devices (Android, iOS, Windows) but Mac can't receive any.

Have tried reconnecting to PushBullet, reset configuration and reinstall but to no avail.

**Comment by fernandex00** [comment]
Same here Ubuntu 19.04

**Comment by danperks** [comment]
Same issue on ElementryOS

**Comment by btaens** [comment]
Same on Pop OS 19.04

**Comment by btaens** [comment]
Still seems to be an issue in v9.0.9.

**Comment by btaens** [comment]
All right, so the issue seems to come from generateNotificationImage() method of push.js.
The method seems to be trying to generate an icon for the notification from various image sources (chat url, sender account image, etc..) and returns whichever gives back a valid image first in a fallback sequence.

However, when it's trying to generate the chat icon, it looks for the open chat room by email with `window.pb.targets.by_email()`. This returns a null object, as a chat room by this email doesn't exist.
It then tries to get the `image_url` property of our null object, which then throws an error, stopping the notification from showing all together.

Relevant code:
https://github.com/sidneys/pb-for-desktop/blob/6f076b4999a29059d921568ff584c11008852c72/app/scripts/renderer/pushbullet/push.js#L285-L288

**Comment by charles-001** [comment]
@btaens,

Thanks for the commit! Unfortunately though, it didn't fix the issue for me. I changed the code to use your commit and re-built it for MacOS, but... it wasn't the magic bullet :( Text messages are still not popping up.

**Comment by GodLesZ** [comment]
Not only MacOS related (please change issue title and labels)
Also don't getting any notifications on my ARCH Linux (Manjaro)

**Comment by GodLesZ** [comment]
Update: The fix from @btaens help's me on ARCH Linux. Using the Android app and typing something in "push", either directed to all or just my PC, will create a notification on linux.

**But** using the _test notification_ button in the Android app doesn't create a notification on linux.
Instead I'm receiving a notification on android.
Also, notifications from Android app's doesn't create a notification on the PC either.
So the fix currently only fixes a potential access on null.

Debugging the `push.js` turns out that `testIfPushIsIgnored` is returning `true`, because the push object doesn't contains a `active` property. 
https://github.com/sidneys/pb-for-desktop/blob/f042bbbaed8c6fcdd12ec86b6f46fa237a2a920c/app/scripts/renderer/pushbullet/push.js#L832-L834

----

Either the android app creates an invalid structure, or the electron app handles the test notification not properly.
Maybe @sidneys can help identifying the problem?

Some self-crafted notification, which works with https://github.com/sidneys/pb-for-desktop/pull/107
```json
{
  "active": true,
  "iden": "xxx",
  "created": 1567401289.72517,
  "modified": 1567401289.758848,
  "type": "note",
  "dismissed": false,
  "guid": "5c61133c-af06-4a78-ab55-ad1008fa47b4",
  "direction": "self",
  "sender_iden": "xxx",
  "sender_email": "xxx",
  "sender_email_normalized": "xxx",
  "sender_name": "GodLesZ Blubb",
  "receiver_iden": "xxx",
  "receiver_email": "xxx",
  "receiver_email_normalized": "xxx",
  "source_device_iden": "xxx",
  "awake_app_guids": [
    "xxx"
  ],
  "body": "Test an alle"
}
```

And here a test notification using the Android app "test" button in the "mirror" tab, which triggers `isIgnored`
```json
{
  "actions": [
    {
      "label": "Fertig",
      "trigger_key": "com.pushbullet.android_3_null_Fertig"
    }
  ],
  "application_name": "Pushbullet",
  "body": "Wenn Sie dies an Ihrem PC sehen, funktioniert die Benachrichtigungsweiterleitung!",
  "client_version": 349,
  "dismissible": true,
  "icon": "some valid base64 hash",
  "notification_id": "3",
  "package_name": "com.pushbullet.android",
  "source_device_iden": "xxx",
  "source_user_iden": "xxx",
  "title": "Testbenachrichtigung",
  "type": "mirror"
}
```

Aaaand during writing this answer, here his again a notification from an Android game app, which triggers `isIgnored` with `true` and is therefore not shown on my linux:
```json
{
  "application_name": "Jurassic Tribes",
  "body": "Eine Sammeltruppe ist ist zurückgekehrt",
  "client_version": 349,
  "dismissible": true,
  "icon": "some valid base64 hash",
  "notification_id": "-261202488",
  "package_name": "com.games37.jc",
  "source_device_iden": "xxx",
  "source_user_iden": "xxx",
  "title": "Jurassic Tribes",
  "type": "mirror"
}
```

---

Lastly, if I try hard commenting out the `active` check, all notifications are directed correctly.
https://github.com/sidneys/pb-for-desktop/blob/f042bbbaed8c6fcdd12ec86b6f46fa237a2a920c/app/scripts/renderer/pushbullet/push.js#L832-L834

But I still don't have any clue about the side effects of this change.

**Comment by charles-001** [comment]
I'm not sure this project is still supported by the developer... my issue has been created for 23 days and no response yet.

**Comment by GodLesZ** [comment]
> I'm not sure this project is still supported by the developer... my issue has been created for 23 days and no response yet.

Yea but he released 9.5.0 just 24 days ago, so it's still active.

**Comment by charles-001** [comment]
Yeah, true. I guess I see this as a fundamental bug w/ the project because of the fact that receiving notifications on PC is the main purpose to use it and I've received 0 support in the past month. I know I'm not paying for it and I'm not owed anything, but I'd think this would be a top priority to fix for usability.

**Comment by gregdotca** [comment]
I'm unable to receive notifications on Linux Mint 19.2, and it sounds like it may be related to this issue.

- My IFTTT applets push notifications to me just fine
- Notifications aren't being mirrored (including SMS notifications)
- I don't receive pushes that I send from my phone
- Universal copy/paste works fine

**Comment by sidneys** [comment]
@vuther 
@GodLesZ 
@shoguevara 

Thanks for all your efforts, comments and documentation. The issue will be addressed asap, there was simply a lack of time. A new version of the project will be released today.

**Comment by sidneys** [comment]
@vuther 
@GodLesZ 
@shoguevara 

Thanks for all your efforts, comments and documentation. Due to a lack of time, work on the issue backlog had been delayed for some time.

The issue was addressed in the new release (with great help via @btaens pull requests) and is available here:
https://github.com/sidneys/pb-for-desktop/releases

Please validate whether the bug still occurs.

Cheers,
S

**Comment by sidneys** [comment]
> I'm unable to receive notifications on Linux Mint 19.2, and it sounds like it may be related to this issue.
> 
>     * My IFTTT applets push notifications to me just fine
> 
>     * Notifications aren't being mirrored (including SMS notifications)
> 
>     * I don't receive pushes that I send from my phone
> 
>     * Universal copy/paste works fine

@chetcuti 

Thanks for the report. Does the issue still persist in  [version 10.2.0](https://github.com/sidneys/pb-for-desktop/releases/tag/v10.2.0)?

Kind Regards, S

**Comment by gregdotca** [comment]
@sidneys, I just installed the most recent version and it seems to have fixed the issues I was having. Notifications are now mirroring and I'm receiving pushes on my desktop that I sent from my phone.

Unfortunately I've actually had to switch away from PB for Desktop though. Since the notifications aren't persistent I've had to switch to the browse extension, which does have persistent notifications. I would prefer to use the actual app but I was missing too many notifications because I rarely look down at my taskbar to see if there are new notifications.
