### ISSUE TITLE
Login stays on Connecting

### ISSUE THREAD

**Issue by ManuNovas** [sidneys/pb-for-desktop#105]
## 🤷🏽‍♂️ Current Behaviour
When I'm trying to connect my google Account, it stays on green "Connecting" window.

## 🎯 Expected Behaviour
I saw that this issue fixed on Ubuntu 18.x but appear again on Ubuntu 19.04

## 👟 Steps to Reproduce (S2R)
1. Click on SingUp with Google:
![image](https://user-images.githubusercontent.com/19921308/61548416-4594f000-aa13-11e9-8eb6-542149031395.png)
2. It appear login form from google but shortly:
![image](https://user-images.githubusercontent.com/19921308/61548473-66f5dc00-aa13-11e9-964d-8f41acd380b1.png)
3. After that, appear the green window
![image](https://user-images.githubusercontent.com/19921308/61548501-75dc8e80-aa13-11e9-8579-6f9aafd9d6f5.png)

## 🏡 Environmental Context
**App Version**
v9.0.9
**Installation Type** 
Setup: Default with rpm package
**Operating System**
Ubuntu 19.04

**Comment by btaens** [comment]
The issue seems to stem from the app attaching a 'did-fail-load' event listener to the WebView that is responsible for the Google OAuth login.

If you check, you can see the issue is not present when you login through Facebook.

Google on the other hand, seems to call a CheckConnection endpoint that it immediately cancels (not sure why, must be some authentication thing), which the pb-for-desktop event handler catches, even though it's a -3 user aborted event, and sends the offline IPC message, which in turn triggers the spinner animation.

Relevant code is at:
https://github.com/sidneys/pb-for-desktop/blob/6f076b4999a29059d921568ff584c11008852c72/app/scripts/renderer/main.js#L196-L203

**Comment by AskAlice** [comment]
@btaens can you build and release? This really breaks for me. Also doesn't work on facebook
edit: a fix I found is, hitting ctrl+shift+I then deleting the spinner element

**Comment by ManuNovas** [comment]
Thank You, Last update allow me login on google.

**Comment by sidneys** [comment]
@ManuNovas The newest release addressed this issue and was just deployed - looking forward to your feedback: https://github.com/sidneys/pb-for-desktop/releases

**Comment by sidneys** [comment]
@ManuNovas @btaens @AskAlice 

The application was just deployed in [version 10.2.0](https://github.com/sidneys/pb-for-desktop/releases/tag/v10.2.0), and the issue could not be reproduced on either macOS or Ubuntu, thus this issue will be closed. If it should however persist or reoccur, please add your feedback.

Kind regards, S

**Comment by jhg03a** [comment]
This appears to have come back with v11.0.2 on an m2 mac.

**Comment by TechnoSwiss** [comment]
Also present again with v11.0.2 on Win10, getting around it with developer mode and deleting the spinner element.

**Comment by SC7639** [comment]
Also, present again for me on mac os v11.0.2
