### ISSUE TITLE
MFA google support

### ISSUE THREAD

**Issue by BastLeblanc** [sidneys/pb-for-desktop#114]
## 🤷🏽‍♂️ Current Behaviour

trying to login through google, I get
You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.

Try using a different browser. Learn more

## 🎯 Expected Behaviour

support MFA google

## 👟 Steps to Reproduce (S2R)

connect using Google, email, password
and got the error

## 🏡 Environmental Context

**App Version**
Version 10.2.0 (10.2.0)
**Installation Type** 
App
**Operating System**
Mac 10.14.6 (18G103)

**Comment by Puremin0rez** [comment]
I can confirm this issue, prevents me from using the app currently since my account can't sign in.

Windows here - so not an OS specific problem.

**Comment by a-katsarov** [comment]
Same error here on Debian 10. Version 10.2.0

**Comment by Govanator12** [comment]
And me in Ubuntu 18.04.3

**Comment by sidneys** [comment]
@BastLeblanc @Puremin0rez @a-katsarov @Govanator12 

Thank you all for the info regarding this bug, which can be easily reproduced when switching any Google login to 2FA. The issue seems to occur due to changes Google implemented within their 2FA flow, as it occurs in other Electron-based apps as well (https://github.com/electron/electron/issues/17887).

A hotfix is already in the works, being released shortly.

Cheers, S

**Comment by sidneys** [comment]
@BastLeblanc @Puremin0rez @a-katsarov @Govanator12

The fix has arrived in v10.3.0.

Cheers, S
