### ISSUE TITLE
[Ubuntu 16.10] Add transparent tray icon

### ISSUE THREAD

**Issue by SolarLiner** [sidneys/pb-for-desktop#44]
With the current design of most DE on Linux it is best to provide transparent tray icons that themes can modulate.

Currently the icon doesn't sit nice currently, and trying to fix it with [Hardcode-tray](https://github.com/bil-elmoussaoui/Hardcode-Tray) doesn't work.

I'll send out a pull request with new icons when I have time.

**Comment by sidneys** [comment]
@SolarLiner 

Thanks for the heads-up. Expecting your PR. :-)

**Comment by bilelmoussaoui** [comment]
@SolarLiner Hey, i'm the dev of Hardcode-Tray, can you please open an upstream issue for that? i woud like to fix that for you :) Thanks

Edit: i have updated the pb-desktop database, the only reason why it's not working in your case is because the theme you're using does not provide those icons yet. Please feel free to report that upstream of whatever theme you're using!

**Comment by SolarLiner** [comment]
Of course that's why. I thought it was converting existing tray icons through Image Magick (or Inkscape, in my case) to "monochromize" them.

I'm using Papirus, which appears to have an icon set for PB for Desktop (the icon changes when changing from Adwaita to Papirus in the Tweak Tool). So it seems it's okay?

**Comment by bilelmoussaoui** [comment]
@SolarLiner Converting icons directly using ImageMagick won't provide the best experience (imagemagick is not that good at doing such things..)
Papirus, might have those icons i got no idea :( the icon shouldn't change as it's hardcoded on the app.asar file which means it can be themed, which is the main reason why i created Hardcode-Tray at first :p
